--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HazardTeam/AutoClearChunk
build-by-default: true
branches:
- main
projects:
  AutoClearChunk:
    path: ""
    icon: "icon.png"
    libs:
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^2.1.0
...
