--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HazardTeam/AutoClearChunk
branches:
- main
projects:
  AutoClearChunk:
    path: ""
    icon: "icon.png"
    libs:
      - src: LatamPMDevs/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
...
