---
name: AutoClearChunk
main: HazardTeam\AutoClearChunk\AutoClearChunk
version: 2.0.0
api: [3.21.0]
author: HazardTeam
description: Auto clear the chunk if there is no player in chunk
website: https://github.com/HazardTeam/AutoClearChunk
...