name: AutoClearChunk
main: hazardteam\autoclearchunk\AutoClearChunk
src-namespace-prefix: hazardteam\autoclearchunk
version: 3.0.0
api: [5.0.0]
author: HazardTeam
description: Auto clears chunks when there are no players present
website: https://github.com/HazardTeam/AutoClearChunk
permissions:
  autoclearchunk.command.clearchunk:
    default: op
    description: Permission to use the ClearChunk command
  autoclearchunk.command.clearallchunk:
    default: op
    description: Permission to use the ClearAllChunk command
