name: AutoClearChunk
main: hazardteam\autoclearchunk\AutoClearChunk
src-namespace-prefix: hazardteam\autoclearchunk
version: 2.2.1
api: [5.0.0]
author: HazardTeam
description: Auto clears chunks when there are no players present
website: https://github.com/HazardTeam/AutoClearChunk
permissions:
  autoclearchunk.clearchunk:
    default: op
    description: Permission to use the ClearChunk command
  autoclearchunk.clearchunkall:
    default: op
    description: Permission to use the ClearAllChunk command
