name: AutoClearChunk
main: HazardTeam\AutoClearChunk\AutoClearChunk
description: clear the chunk if there is no player in chunk
version: 2.0.0
api: 3.0.0
author: HazardTeam
website: https://github.com/HazardTeam
