# AutoClearChunk Configuration

# Enable Auto Schedule
# Determines whether the plugin automatically schedules the task to clear unloaded chunks at the specified interval.
# Set to 'true' to enable auto schedule, 'false' to disable.
enable-auto-schedule: true

# Clear Interval Duration
# Determines the time interval at which unloaded chunks are automatically cleared.
# The value should be specified as a duration format string.
# Examples: 1h (1 hour), 30m (30 minutes), 15s (15 seconds)
clear-interval-duration: 5m30s

# Message displayed when chunks are cleared using the ClearChunk command
# Use %d placeholder for the number of cleared chunks and %s placeholder for the world name.
# You can customize the message using color codes.
# Default: "Successfully cleared %d chunks in world %s"
clearchunk-message: "&aSuccessfully cleared %d chunks in world %s"

# Message broadcasted to all players when chunks are cleared using the ClearChunk command
# Use %d placeholder for the number of cleared chunks and %s placeholder for the world name.
# You can customize the message using color codes.
# Default: "&e%d chunks have been cleared in world %s"
clearchunk-broadcast-message: "&e%d chunks have been cleared in world %s"

# Message displayed when chunks are cleared using the ClearAllChunk command
# Use %d placeholder for the number of cleared chunks.
# You can customize the message using color codes.
# Default: "Successfully cleared %d chunks in all worlds"
clearallchunk-message: "&aSuccessfully cleared %d chunks in all worlds"

# Message broadcasted to all players when chunks are cleared using the ClearAllChunk command
# Use %d placeholder for the number of cleared chunks.
# You can customize the message using color codes.
# Default: "&e%d chunks have been cleared in all worlds"
clearallchunk-broadcast-message: "&e%d chunks have been cleared in all worlds"

# Enable or Disable Message broadcast to all players when chunk are cleared
broadcast-message: true

# List of worlds that are blacklisted and won't be cleared
# Add the names of any worlds you want to exclude from the clearing process.
# Default: []
blacklisted-worlds:
  - your_world
  - another_world
