# AutoClearChunk Configuration

# Enable Auto-Schedule
# Determines whether the plugin automatically schedules the task to clear unloaded chunks at the specified interval.
# Set to 'true' to enable auto-scheduling, 'false' to disable.
enable-auto-schedule: true

# Clear Interval Duration
# Defines the time interval at which unloaded chunks are automatically cleared.
# The value should be specified in a duration format.
# Examples: 1h (1 hour), 30m (30 minutes), 15s (15 seconds)
clear-interval-duration: 5m30s

# Chunk Unload Grace Period Duration
# Specifies how long a chunk without players should wait before being considered for unloading.
# Set to "0s" to disable the grace period and unload instantly (reverts to old behavior).
# Examples: 30s, 5m, 1h
chunk-unload-grace-period-duration: "30s"

# Clear Chunk Message
# Message displayed when chunks are cleared using the /clearchunk command.
# Use %d as a placeholder for the number of cleared chunks and %s for the world name.
# Color codes are supported.
# Default: "&aSuccessfully cleared %d chunks in world %s"
clearchunk-message: "&aSuccessfully cleared %d chunks in world %s"

# Clear Chunk Broadcast Message
# Message broadcast to all players when chunks are cleared using the /clearchunk command.
# Use %d as a placeholder for the number of cleared chunks and %s for the world name.
# Color codes are supported.
# Default: "&e%d chunks have been cleared in world %s"
clearchunk-broadcast-message: "&e%d chunks have been cleared in world %s"

# Clear All Chunk Message
# Message displayed when chunks are cleared using the /clearallchunk command.
# Use %d as a placeholder for the number of cleared chunks.
# Color codes are supported.
# Default: "&aSuccessfully cleared %d chunks in all worlds"
clearallchunk-message: "&aSuccessfully cleared %d chunks in all worlds"

# Clear All Chunk Broadcast Message
# Message broadcast to all players when chunks are cleared using the /clearallchunk command.
# Use %d as a placeholder for the number of cleared chunks.
# Color codes are supported.
# Default: "&e%d chunks have been cleared in all worlds"
clearallchunk-broadcast-message: "&e%d chunks have been cleared in all worlds"

# Enable Broadcast Messages
# Set to 'true' to enable broadcasting messages to all players when chunks are cleared, 'false' to disable.
broadcast-message: true

# Blacklisted Worlds
# List of world names that will be excluded from the chunk clearing process.
# Add the exact names of any worlds you want to exclude.
# Default: []
blacklisted-worlds:
  - your_world
  - another_world
